### ISSUE TITLE
Parameter for script

### ISSUE THREAD

**Issue by manfredlotz** [tusharsadhwani/zxpy#17]
In a bash or python script I could have parameters when calling it. This seems to be impossible when using zxpy.

Example:

`myscript /home` 

gives

```
Traceback (most recent call last):
  File "/home/manfred/.local/bin/zxpy", line 8, in <module>
    sys.exit(cli())
  File "/home/manfred/.local/lib/python3.8/site-packages/zx.py", line 54, in cli
    with open(filename) as file:
IsADirectoryError: [Errno 21] Is a directory: '/home'
```

Is there a way I just overlooked?

**Comment by tusharsadhwani** [comment]
can you share the code in `myscript`?

It seems that you're trying to do a file-specific action on a directory, like `cat`, which is throwing this error.

**Comment by manfredlotz** [comment]
Let's say I would have something like this

```
#! /usr/bin/env zxpy
import sys


def main():
    dir = sys.argv[1]
    print(f"Backing up directory {dir}")
    ~f'mybackup {dir}'


if __name__ == "__main__":
    main()
```

**Comment by tusharsadhwani** [comment]
@manfredlotz it should work perfectly fine as long as running `mybackup <directory>` doesn't crash in a regular terminal.

If you're still confused, send me a working code snippet that crashes for you and I can help you out :)

**Comment by manfredlotz** [comment]
The script above doesn't run fine here

```
 ./myscript.py /home
Traceback (most recent call last):
  File "/home/manfred/.local/bin/zxpy", line 8, in <module>
    sys.exit(cli())
  File "/home/manfred/.local/lib/python3.8/site-packages/zx.py", line 55, in cli
    with open(filename) as file:
IsADirectoryError: [Errno 21] Is a directory: '/home'
```

**Comment by tusharsadhwani** [comment]
OH, I see the issue. Sorry, my bad. Took too long to figure out what's going on.

**Comment by tusharsadhwani** [comment]
I'll explain what's going on:

- `./myscript.py /home` turns into `zxpy ./myscript.py /home` because of the shebang (`#! /usr/bin/env zxpy`)
- `zxpy` tries to treat every argument in `sys.argv` as a file to execute.

This was added to support piping, like:
```bash
$ ls | grep '\.py$' | zxpy
```

But it seems this behaviour is a bit odd. I'll think about a solution and get back to you.

**Comment by manfredlotz** [comment]
At least, this behavior makes normal scrip usage with parameters impossible.

Thanks a lot for looking into this.

**Comment by tusharsadhwani** [comment]
So I actually found two issues in this:

- `zxpy myscript.py /home` was being treated as running two programs: `zxpy myscript.py` and `zxpy /home`. This is why it was crashing.

- The `__name__` value was actually wrong! That's why `zxpy myscript.py` wasn't doing anything. Otherwise it would've ran fine on the first command (as `sys.argv[1]` was still `/home`), and then crashed when it tried to run the second time.

Anyway, both issues have now been fixed in v1.4.1.

Try running `pip install -U zxpy` and try your script again, and let me know if it works :)

**Comment by manfredlotz** [comment]
Looks good now. Thanks for you quick support.

**Comment by digitalsignalperson** [comment]
This is broken using v1.6.2

script.py
```
#!/usr/bin/env zxpy

~'echo Hello world!'

x = sys.argv[1]
print(x)
```

trying to run
```
./script.py x
usage: zxpy [-h] [-i] [filename]
zxpy: error: unrecognized arguments: x
```


solved with changing

```
args = parser.parse_known_args(namespace=ZxpyArgs())
```

to

```
args, unknown = parser.parse_known_args(namespace=ZxpyArgs())
```

but now I also noticed `NameError: name 'sys' is not defined` so I have to `import sys`. I'm not sure if zxpy is supposed to import that ahead (judging by the OP's script).

I also noticed `~'echo $1'` does not know about the arguments either, but that doesn't necessarily need to be a feature.

**Comment by tusharsadhwani** [comment]
I can probably add this behind a `--`, like so:

```bash
./script.py -- x
```

that will ensure that zxpy arguments and the arguments to the script itself don't get conflicts.

I'll work on this today.

**Comment by tusharsadhwani** [comment]
`echo $1`, I'll have to try to work it in to see what challenges it can give. But I'll give it a shot.

**Comment by tusharsadhwani** [comment]
@digitalsignalperson New version has been released, can you check if it works fine now?

```
pip install zxpy==1.6.3
```
