### ISSUE TITLE
Documenting what syntax works and what doesn't

### ISSUE THREAD

**Issue by manfredlotz** [tusharsadhwani/zxpy#24]
In the `zxpy` repl I tried various ways of issuing a cmd and some did not work.

```
zxpy shell
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]

>>> ~'uname'
Linux
>>> cmd = 'uname'
>>> ~f'{cmd}'
Linux
>>> ~cmd
Traceback (most recent call last):
  File "/home/manfred/.local/lib/python3.8/site-packages/zx.py", line 295, in install
    exec(code_obj)
  File "<input>", line 1, in <module>
TypeError: bad operand type for unary ~: 'str'
>>> cmd = 'uname -a'
>>> ~f'{cmd}'
/bin/sh: 1: uname -a: not found
>>> ~cmd
Traceback (most recent call last):
  File "/home/manfred/.local/lib/python3.8/site-packages/zx.py", line 295, in install
    exec(code_obj)
  File "<input>", line 1, in <module>
TypeError: bad operand type for unary ~: 'str'
```

**Comment by tusharsadhwani** [comment]
Problem 1, `~cmd` is an unfortunate outcome from how the library is set up. Since the AST doesn't know by the structure of that statement that `cmd` is a string, it cannot guarantee that `~cmd` is a zxpy command instead of a python operator. For example:

```pycon
>>> cmd = 42
>>> ~cmd
-43
```

Problem 2 is because I added escaping logic to bash f-strings, to avoid shell injection.

---

`~f'{cmd}'` is the same as running `'uname -a'` in your terminal, instead of `uname -a` (notice the quoting).

This is something I'm willing to take input on. Should I maybe add a config option to enable/disable quoting of f-string variables?

**Comment by manfredlotz** [comment]
Reading you explanations I am not sure if something should be done at all.  Perhaps it is enough to just document this in some way.

**Comment by tusharsadhwani** [comment]
Perhaps.

I'll keep this issue open, as I'm not 100% sure what to do yet.

**Comment by tusharsadhwani** [comment]
I just realised it could be possible to simply add a format spec to tell zxpy to not quote an instance of the usage, something like `~f'{cmd:!}` or `~f'{cmd:raw}`. I'll try those out tomorrow.

**Comment by tusharsadhwani** [comment]
[v1.4.5](https://github.com/tusharsadhwani/zxpy/releases/tag/1.4.5) is released, now `~f'{cmd:raw}'` should work :)

**Comment by tusharsadhwani** [comment]
@manfredlotz @jack1142 do drop your thoughts

**Comment by jack1142** [comment]
Assuming it works (can't really check right now), I think it's awesome you managed to support both ways with an easy syntax like this :) I also like that the default remained the same as it should help people avoid introducing shell injection by accident.

**Comment by manfredlotz** [comment]
`~f'{cmd:raw}'` works fine. Looks like a good solution. Thanks a lot, @tusharsadhwani
